const BLUE = '#347AF0';
const WHITE = '#FFF';
const DISABLE = '#B5BBC9';
const TEXT_BLACK = '#0D1F3C';
const TEXT_GRAY = '#78839C';
const GREEN = '#75BF72';
const LIGHT_GREEN = '#00ff55';
const BG_LIGHT_GRAY = '#CFD2D8';
const BG_LIGHTIEST_GRAY = '#EDF1F9';
const YELLOW = '#E4BC2D';

export {
  YELLOW,
  BLUE,
  WHITE,
  DISABLE,
  TEXT_BLACK,
  TEXT_GRAY,
  GREEN,
  BG_LIGHT_GRAY,
  BG_LIGHTIEST_GRAY,
  LIGHT_GREEN,
};
